ALTER TABLE plots ADD COLUMN IF NOT EXISTS price INTEGER;
ALTER TABLE plots ADD COLUMN IF NOT EXISTS wage INTEGER;
ALTER TABLE plots ADD COLUMN IF NOT EXISTS staff_json TEXT;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'transfer';
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS debited INTEGER NOT NULL DEFAULT 1;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS plot TEXT;
CREATE INDEX IF NOT EXISTS transfers_plot ON transfers (plot, kind, at);
